version: '4.17'
services:
  backend:
    build: .
    # command: bash -c 'while !</dev/tcp/db/3306; do sleep 1; done; npm start'
    ports:
      - 8000:3000
    volumes:
    - .:/app
    depends_on:
      - db

  db:
    image: mysql:5.7.41
    restart: always
    environment:
      MYSQL_DATABASE: ambassador
      MYSQL_ALLOW_EMPTY_PASSWORD: ok
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 3306:3306
    
    # need to update port in case if mysql is installed locally:
    # ports:
    #   - 33066:3306